# Generated by Django 2.2.4 on 2019-08-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momoapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='momorequest',
            name='request',
        ),
        migrations.AddField(
            model_name='momorequest',
            name='request_status',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='momorequest',
            name='request_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
